/** Full A2UI catalog and example, disclosed with the render_cards input schema. */
export const RENDER_CARDS_SCHEMA_GUIDANCE = [
  "Render a structured, interactive answer with the A2UI v1.0 protocol.",
  "You MUST use this for answers with 2+ figures, comparisons, tables, findings,",
  "decisions, configuration forms, or recovery actions. The surface is canonical:",
  "do not repeat its prose or figures in the final message.",
  "Call the tool with `{messages:[...]}`. New surfaces use one createSurface message with",
  '`version:"v1.0"`, catalogId `urn:openneko:catalog:work:v2`, globally unique surfaceId,',
  "components, and an initial dataModel. Every surface has a component with id `root`.",
  "Property bindings use `{ path: \"/json/pointer\" }`.",
  "",
  "Catalog components:",
  "- Answer: answer frame. Props title, subtitle?, eyebrow?, children[].",
  "- Markdown: narrative markdown. Prop text.",
  "- Text: compact text. Props text, variant? (`body` or `caption`).",
  "- KeyFigures: cardless ruled evidence strip. Props items[{label,value,sub?,basis?,asOf?,source?}].",
  "- MetricCard: KPI. Props metricId, source, mood, text, metric, label, detail, chartType, chartData.",
  "- Chart: standalone evidence chart. Props title, type (`line`|`bar`|`area`|`donut`),",
  "  data[{d:string label,v:number,t?:number}], valueLabel, baselineLabel?, source?, asOf?.",
  "- Table: structured results. Props columns[{key,label,align?}], rows[], caption?.",
  "- Callout: operational status/takeaway. Props mood (`good`|`watch`|`act`), title?, text.",
  "- Section: titled group. Props title, children[], collapsible?, defaultOpen?.",
  "- Row / Column: layout containers. Props children[], justify?, align?.",
  "- Tabs: tabbed detail. Props tabs[{title,child}].",
  "- TextField: bound input. Props label, value?, placeholder?, variant?",
  "  (`shortText`|`longText`|`number`|`obscured`).",
  "- CheckBox: bound boolean. Props label, value.",
  "- ChoicePicker: bound string-array selection. Props label?, options[{label,value}],",
  "  value, variant? (`mutuallyExclusive`|`multipleSelection`), displayStyle?.",
  "- Conditional: reactive child group. Props when (usually a path binding), children[],",
  "  and either equals or oneOf[]. Arrays match when they contain an allowed value.",
  "- OpenApiSpecInput: admin import control for hosted URL or YAML/JSON upload. Bind `value`",
  "  to a dataModel object; the server fills it with validated metadata and a managed asset id.",
  "- ManagedFileSourceInput: admin upload control for an isolated local file source. Bind",
  "  `sourceName` to the source name and `value` to a dataModel object containing staged files.",
  "- Button: action button. Props child (a Text component id), variant, action.event,",
  "  and optional `requires` binding that enables the action after a value exists.",
  "- Choice: quick follow-up buttons. Props options[{label,prompt,mood?}].",
  "- Divider: separator. Props label?.",
  "",
  "For editable configuration, bind each field to the dataModel. Put only top-level",
  "component ids in root.children. Use Conditional groups for kind-specific fields.",
  "A mutuallyExclusive ChoicePicker stores a one-item string array. A submit Button uses",
  "`action.event.name` plus context `{ prompt: <clear next instruction>, values: {path:\"/form\"} }`.",
  "The operator's submitted values arrive in the next turn. Validate them, then use the",
  "appropriate proposal tool so the existing approval policy remains the commit boundary.",
  "Use `secretRef` names in forms for credentials.",
  "Prefer KeyFigures for headline answer numbers. Use MetricCard for a saved",
  "KPI with mood context; use Chart for an ad hoc visualization in an answer.",
  "Choose Chart only when a trend, comparison, or category mix is easier to see",
  "than read. Use line/area for ordered time points, bar for comparisons, and",
  "donut for 2–8 nonnegative parts of a whole. Use at most 60 actual data points.",
  "Do not invent or interpolate points; label the measure, time window, and source.",
  "For a single number use KeyFigures; for exact row values use Table as needed.",
  "If sandbox network access is denied, render only the denial/recovery facts.",
  "Never substitute seasonal norms or invented values for unavailable live data.",
  "",
  "Example — chart in an answer (use verified values from this turn):",
  '{"messages":[{"version":"v1.0","createSurface":{"surfaceId":"trend-<unique>","catalogId":"urn:openneko:catalog:work:v2","dataModel":{},"components":[{"id":"root","component":"Answer","title":"Weekly orders","children":["trend"]},{"id":"trend","component":"Chart","title":"Orders by week, September 2026","type":"line","data":[{"d":"Sep 7","v":42},{"d":"Sep 14","v":47},{"d":"Sep 21","v":44}],"valueLabel":"Orders","source":"Orders database","asOf":"Sep 21, 2026"}]}}]}',
  "",
  "Example — editable source proposal:",
  "{",
  '  "messages": [',
  '  {"version":"v1.0","createSurface":{',
  '    "surfaceId":"source-form-<unique>","catalogId":"urn:openneko:catalog:work:v2",',
  '    "dataModel":{"form":{"name":"","kind":["database"],"type":"postgres","host":"","port":5432,"dbname":"","user":"","secretRef":"","openApiSpec":null,"backend":["local"],"localFiles":null,"bucket":"","prefix":"","region":"","endpoint":"","publicBaseUrl":"","presignTtl":"15m"}},',
  '    "components":[',
  '      {"id":"root","component":"Answer","eyebrow":"GRAPHJIN CONFIG","title":"Add a source","subtitle":"Choose a source type and provide its connection details.","children":["note","common","databaseFields","apiFields","fileFields","databaseSubmit","apiSubmit","fileSubmit"]},',
  '      {"id":"note","component":"Callout","mood":"watch","title":"Approval required","text":"Submitting creates a configuration proposal for admin review."},',
  '      {"id":"common","component":"Column","children":["name","kind"]},',
  '      {"id":"name","component":"TextField","label":"Source name","value":{"path":"/form/name"},"placeholder":"warehouse"},',
  '      {"id":"kind","component":"ChoicePicker","label":"Source kind","options":[{"label":"Database","value":"database"},{"label":"API","value":"api"},{"label":"Files","value":"file"}],"value":{"path":"/form/kind"},"variant":"mutuallyExclusive"},',
  '      {"id":"databaseFields","component":"Conditional","when":{"path":"/form/kind"},"equals":"database","children":["type","network","database"]},',
  '      {"id":"type","component":"TextField","label":"Database type","value":{"path":"/form/type"},"placeholder":"postgres"},',
  '      {"id":"network","component":"Row","children":["host","port"]},',
  '      {"id":"host","component":"TextField","label":"Host","value":{"path":"/form/host"},"placeholder":"db.internal"},',
  '      {"id":"port","component":"TextField","label":"Port","value":{"path":"/form/port"},"variant":"number"},',
  '      {"id":"database","component":"Row","children":["dbname","user","secretRef"]},',
  '      {"id":"dbname","component":"TextField","label":"Database","value":{"path":"/form/dbname"}},',
  '      {"id":"user","component":"TextField","label":"User","value":{"path":"/form/user"}},',
  '      {"id":"secretRef","component":"TextField","label":"Stored secret name","value":{"path":"/form/secretRef"},"placeholder":"warehouse-password"},',
  '      {"id":"apiFields","component":"Conditional","when":{"path":"/form/kind"},"equals":"api","children":["openApiSpec"]},',
  '      {"id":"openApiSpec","component":"OpenApiSpecInput","label":"OpenAPI specification","value":{"path":"/form/openApiSpec"}},',
  '      {"id":"fileFields","component":"Conditional","when":{"path":"/form/kind"},"equals":"file","children":["fileSecurity","backend","localFields","objectFields","s3Fields"]},',
  '      {"id":"fileSecurity","component":"Callout","mood":"watch","title":"Read-only source","text":"Authenticated organization members receive list/read access to approved file content."},',
  '      {"id":"backend","component":"ChoicePicker","label":"Storage backend","options":[{"label":"Local","value":"local"},{"label":"S3","value":"s3"},{"label":"GCS","value":"gcs"}],"value":{"path":"/form/backend"},"variant":"mutuallyExclusive"},',
  '      {"id":"localFields","component":"Conditional","when":{"path":"/form/backend"},"equals":"local","children":["managedFiles"]},',
  '      {"id":"managedFiles","component":"ManagedFileSourceInput","label":"Managed local files","sourceName":{"path":"/form/name"},"value":{"path":"/form/localFiles"}},',
  '      {"id":"objectFields","component":"Conditional","when":{"path":"/form/backend"},"oneOf":["s3","gcs"],"children":["cloudCredentials","bucket","prefix","publicBaseUrl","presignTtl"]},',
  '      {"id":"cloudCredentials","component":"Callout","mood":"watch","title":"Deployment credentials","text":"GraphJin uses its AWS or Google Cloud runtime identity; chat and approval carry storage metadata."},',
  '      {"id":"bucket","component":"TextField","label":"Bucket","value":{"path":"/form/bucket"}},',
  '      {"id":"prefix","component":"TextField","label":"Key prefix","value":{"path":"/form/prefix"}},',
  '      {"id":"publicBaseUrl","component":"TextField","label":"Public HTTPS base URL (optional)","value":{"path":"/form/publicBaseUrl"}},',
  '      {"id":"presignTtl","component":"TextField","label":"Presigned URL TTL","value":{"path":"/form/presignTtl"},"placeholder":"15m"},',
  '      {"id":"s3Fields","component":"Conditional","when":{"path":"/form/backend"},"equals":"s3","children":["region","endpoint"]},',
  '      {"id":"region","component":"TextField","label":"Region","value":{"path":"/form/region"}},',
  '      {"id":"endpoint","component":"TextField","label":"S3-compatible endpoint","value":{"path":"/form/endpoint"}},',
  '      {"id":"submitLabel","component":"Text","text":"Review proposal"},',
  '      {"id":"databaseSubmit","component":"Conditional","when":{"path":"/form/kind"},"equals":"database","children":["submitDatabase"]},',
  '      {"id":"apiSubmit","component":"Conditional","when":{"path":"/form/kind"},"equals":"api","children":["submitApi"]},',
  '      {"id":"fileSubmit","component":"Conditional","when":{"path":"/form/kind"},"equals":"file","children":["localSubmit","s3Submit","gcsSubmit"]},',
  '      {"id":"localSubmit","component":"Conditional","when":{"path":"/form/backend"},"equals":"local","children":["submitLocalFile"]},',
  '      {"id":"s3Submit","component":"Conditional","when":{"path":"/form/backend"},"equals":"s3","children":["submitCloudFile"]},',
  '      {"id":"gcsSubmit","component":"Conditional","when":{"path":"/form/backend"},"equals":"gcs","children":["submitCloudFile"]},',
  '      {"id":"submitDatabase","component":"Button","child":"submitLabel","variant":"primary","requires":{"path":"/form/name"},"action":{"event":{"name":"submit_source_config","context":{"prompt":"Review the selected source kind and its relevant values, then file the register_source configuration proposal.","values":{"path":"/form"}}}}},',
  '      {"id":"submitApi","component":"Button","child":"submitLabel","variant":"primary","requires":[{"path":"/form/name"},{"path":"/form/openApiSpec/id"}],"action":{"event":{"name":"submit_source_config","context":{"prompt":"Use openApiSpec.id as specAssetId and file the register_source API configuration proposal.","values":{"path":"/form"}}}}},',
  '      {"id":"submitLocalFile","component":"Button","child":"submitLabel","variant":"primary","requires":[{"path":"/form/name"},{"path":"/form/localFiles/sourceName"}],"action":{"event":{"name":"submit_source_config","context":{"prompt":"Create the read-only local file source proposal using the managed localFiles manifest and selected source name.","values":{"path":"/form"}}}}},',
  '      {"id":"submitCloudFile","component":"Button","child":"submitLabel","variant":"primary","requires":[{"path":"/form/name"},{"path":"/form/bucket"}],"action":{"event":{"name":"submit_source_config","context":{"prompt":"Create the read-only cloud file source proposal using the selected backend, bucket, prefix, endpoint, public base URL, and bounded presign TTL values.","values":{"path":"/form"}}}}}',
  "    ]",
  "  }}",
  "  ]",
  "}",
].join("\n");
