import { mkdtemp, mkdir, writeFile, readFile, access, rm, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, expect, it } from 'vitest';
import { acquireStableSandboxInputs, clearStableSandboxInputs } from '../src/work/sandbox-staging-cache';
const roots: string[] = [];
afterEach(async () => { await clearStableSandboxInputs(); await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
async function fixture() {
  const orgRoot = await mkdtemp(path.join(tmpdir(), 'staging-cache-test-')); roots.push(orgRoot);
  const workspace = { orgRoot, skillsRoot: path.join(orgRoot, 'skills'), knowledgeRoot: path.join(orgRoot, 'knowledge') };
  await mkdir(workspace.skillsRoot); await mkdir(workspace.knowledgeRoot);
  await writeFile(path.join(workspace.knowledgeRoot, 'catalog'), 'revision one');
  return workspace;
}
it('shares immutable snapshots and retains old generations while concurrent turns use them', async () => {
  const workspace = await fixture();
  const [first, same] = await Promise.all([acquireStableSandboxInputs(workspace), acquireStableSandboxInputs(workspace)]);
  expect(first.root).toBe(same.root);
  expect(first.manifest).toBe(same.manifest);
  await writeFile(path.join(workspace.knowledgeRoot, 'catalog'), 'revision two');
  const next = await acquireStableSandboxInputs(workspace);
  expect(next.root).not.toBe(first.root);
  expect(await readFile(path.join(first.root, 'knowledge', 'catalog'), 'utf8')).toBe('revision one');
  expect(await readFile(path.join(next.root, 'knowledge', 'catalog'), 'utf8')).toBe('revision two');
  await first.release(); await access(same.root);
  await same.release(); await expect(access(first.root)).rejects.toThrow();
  await next.release();
});
it('invalidates library and skill edits and never includes thread uploads or personal memory', async () => {
  const workspace = await fixture();
  for (const name of ['library/okf','skills/custom','memory','uploads/thread']) await mkdir(path.join(workspace.orgRoot, name), { recursive: true });
  await writeFile(path.join(workspace.skillsRoot, 'custom/SKILL.md'), 'custom skill');
  await writeFile(path.join(workspace.orgRoot, 'library/okf/team.json'), 'team v1');
  await writeFile(path.join(workspace.orgRoot, 'memory/private'), 'private');
  await writeFile(path.join(workspace.orgRoot, 'uploads/thread/private'), 'private');
  const first = await acquireStableSandboxInputs(workspace);
  expect(first.skillOverrides).toEqual(['custom']);
  expect(Object.keys(first.manifest.entries).some(key => /memory|uploads/.test(key))).toBe(false);
  await writeFile(path.join(workspace.orgRoot, 'library/okf/team.json'), 'team v2');
  await writeFile(path.join(workspace.skillsRoot, 'custom/SKILL.md'), 'updated skill');
  const second = await acquireStableSandboxInputs(workspace);
  expect(second.revision).not.toBe(first.revision);
  expect(await readFile(path.join(second.root, 'skills/custom/SKILL.md'), 'utf8')).toBe('updated skill');
  await first.release(); await second.release();
});
it('keeps organizations separate and rejects links out of stable input trees', async () => {
  const a = await fixture(), b = await fixture();
  const first = await acquireStableSandboxInputs(a), second = await acquireStableSandboxInputs(b);
  expect(first.root).not.toBe(second.root);
  await first.release(); await second.release();
  await symlink(b.knowledgeRoot, path.join(a.knowledgeRoot, 'outside'));
  await expect(acquireStableSandboxInputs(a)).rejects.toThrow('Unsupported stable');
});
it('keys catalog generations to the atomic snapshot, ignoring in-progress publisher files', async () => {
  const workspace = await fixture();
  const files = { 'tables.json': '{}', 'namespaces.json': '{}', 'insights.json': '{}', 'syntax.json': '{}', 'INDEX.md': 'catalog one', 'mode.json': '{}' };
  const publish = (revision: string) => writeFile(path.join(workspace.knowledgeRoot, '.knowledge-snapshot.json'), JSON.stringify({ format: 1, source: 'test', revision, builtAt: 1, files }));
  await publish('one');
  const first = await acquireStableSandboxInputs(workspace);
  await mkdir(path.join(workspace.knowledgeRoot, '.build-in-progress'));
  await writeFile(path.join(workspace.knowledgeRoot, '.build-in-progress/partial'), 'not published');
  const same = await acquireStableSandboxInputs(workspace);
  expect(same.root).toBe(first.root);
  expect(same.hit).toBe(true);
  expect(Object.keys(same.manifest.entries).some(key => key.includes('partial'))).toBe(false);
  files['INDEX.md'] = 'catalog two'; await publish('two');
  const next = await acquireStableSandboxInputs(workspace);
  expect(next.root).not.toBe(first.root);
  expect(await readFile(path.join(next.root, 'knowledge/INDEX.md'), 'utf8')).toBe('catalog two');
  await first.release(); await same.release(); await next.release();
});
