import { beforeEach, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ query: vi.fn(), workflow: vi.fn(), createRun: vi.fn() }));
vi.mock("@neko/db", async original => ({ ...await original<typeof import("@neko/db")>(), pool: () => ({ query: mocks.query }) }));
vi.mock("../src/workflows/store", async original => ({ ...await original<typeof import("../src/workflows/store")>(), getWorkflow: mocks.workflow, createWorkflowRun: vi.fn(async () => ({ id: "workflow-run" })) }));
vi.mock("../src/work/store", async original => ({ ...await original<typeof import("../src/work/store")>(), createWorkThread: vi.fn(async () => ({ id: "thread" })), createWorkRun: mocks.createRun }));
import { prepareWorkflowRun } from "../src/workflows/run-workflow-turn";
const backend = { id: "hermes" } as Awaited<ReturnType<NonNullable<Parameters<typeof prepareWorkflowRun>[1]>["resolveAgentBackend"]>>;
beforeEach(() => { vi.clearAllMocks(); mocks.createRun.mockResolvedValue({ id: "run" }); mocks.workflow.mockResolvedValue({ id: "wf", orgId: "org", enabled: true, ownerUserId: "alice", name: "Personal" }); });
it("runs as the active owner, rejects a disabled owner, and leaves ownerless runs as service", async () => {
  const input = { orgId: "org", workflowId: "wf", triggerKind: "schedule" as const };
  mocks.query.mockResolvedValue({ rows: [{ role: "member" }] });
  await prepareWorkflowRun(input, { resolveAgentBackend: async () => backend });
  expect(mocks.createRun).toHaveBeenLastCalledWith("org", "thread", "hermes", { userId: "alice", role: "member" });
  mocks.query.mockResolvedValue({ rows: [] }); mocks.createRun.mockClear();
  await expect(prepareWorkflowRun(input, { resolveAgentBackend: async () => backend })).rejects.toThrow("no longer active");
  expect(mocks.createRun).not.toHaveBeenCalled();
  mocks.workflow.mockResolvedValue({ id: "wf", enabled: true, ownerUserId: "", name: "Shared" });
  await prepareWorkflowRun(input, { resolveAgentBackend: async () => backend });
  expect(mocks.createRun).toHaveBeenLastCalledWith("org", "thread", "hermes", { userId: null, role: "service" });
});
